eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9098
spring:
  application:
    name: Training-service
  datasource:
    url: jdbc:mysql://localhost:3306/TrainingManagementSystem
    username: root
    password: pass@word1
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
