eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9761/eureka/
server:
  port: 9099
spring:
  application:
    name: Trainer-service
  datasource:
    url: jdbc:mysql://localhost:3306/Training
    username: root
    password: pass@word1
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
